sonar.projectKey=theo550_glowup
sonar.organization=theo550

sonar.exclusions=**/entity/**, **/dto/**, **/config/**, **/*Generated.java

sonar.host.url=https://sonarcloud.io

# Rapport de couverture JaCoCo
sonar.coverage.jacoco.xmlReportPaths =target/site/jacoco/jacoco.xml
