name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches : [master]

env:
  JAVA_VERSION: '21'
  REGISTRY: docker.io
  IMAGE_NAME: glowcommerce/backend

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
        fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 1. SAST - SonarCloud
      - name: SonarCloud Scan
        run: mvn verify sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 2. SCA - OWASP Dependency Check
      - name: Dependency Check
        run: mvn org.owasp:dependency-check-maven:check