name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches : [master]

env:
  JAVA_VERSION: '21'
  REGISTRY: docker.io
  IMAGE_NAME: glowcommerce/backend

jobs:
  security-scan:
    runs-on: ubuntu-latest
    working-directory: glowcommerce-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        working-directory: glowcommerce-backend
        run: mvn -B clean verify

      - name: SonarCloud Scan
        working-directory: glowcommerce-backend
        run: |
          mvn -B sonar:sonar \
            -Dsonar.projectKey=theo550_glowup \
            -Dsonar.organization=theo550 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # 2. SCA - OWASP Dependency Check
      - name: Dependency Check
        working-directory: glowcommerce-backend
        run: mvn org.owasp:dependency-check-maven:check